services:
  - type: web
    name: spam-classifier
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
